spring:
  application:
    name: BasicLogin
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce_db
    username: postgres
    password: keat6951
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: Password123!
  bucket-name: e-commerce-bucket
server:
  port: 9090