spring:
  config:
    import: "optional:file:./.env[.properties]"
  application:
    name: BasicLogin
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce_db
    username: postgres
    password: keat6951
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2MB
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: Password123!
  bucket-name: e-commerce-bucket
server:
  port: 9090
  tomcat:
    max-swallow-size: 50MB
    max-http-form-post-size: 50MB
bakong:
  base-url: ${BAKONG_BASE_URL:https://api-bakong.nbc.gov.kh}
  email: ${BAKONG_EMAIL:}
  account-id: ${BAKONG_ACCOUNT_ID:}
